name: Code Quality

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  pylint:

    name: pylint
    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
        architecture: x64

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install pylint

    - name: Lint
      run: pylint *.py --disable=missing-module-docstring,missing-class-docstring,missing-function-docstring

  pycodestyle:

    name: pycodestyle
    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
        architecture: x64

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install pycodestyle

    - name: Codestyle
      run: pycodestyle *.py
